name = "MERIT"
uuid = "0c276b8d-6eb3-44a0-a3a7-2fd8fb8ab939"
authors = ["Aaron Dinesh"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
BenchmarkTools = "1"
CSV = "0.10"
DataFrames = "1"
Debugger = "0.7"
DelimitedFiles = "1"
MAT = "0.10"
PlotlyJS = "0.18"
Plots = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
